### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Blackfoxx88** [bhrama-br/spacecrypto-bombcrypto-bot#1]
Not working. it closes the window. But i love the idea BOMBCRYPTO and SPACECRYPTO on one autoclicker. Hope that this will be up and running.

**Comment by bhrama-br** [comment]
It's working for 2 resolutions only!

1920x1080 accurate is at 100% scale

1600x900 accurate is at 150% scale

Cannot have Folder or Anything other than games, name with BombCrypto or SpaceCrypto.

I made an att now

**Comment by Nbonadia** [comment]
@bhrama-br

O bot simplesmente não funciona aqui pra mim. E olha que eu já estou acostumado a usar esse tipo de bot no bombcrypto.

Rez está em 1080p, atualizei todas as fotos só pra ter certeza, mas nada adianta. 

O bot é bem "confuso", as vezes ele clica em play, as vezes não. As vezes ele fica travado na tela inicial e não faz nada. Quando ele finalmente bota naves pra lutar, ele não volta pra tela inicial, fica parada na tela de boss mesmo com todas as naves já estando zeradas.

**Comment by bhrama-br** [comment]
@Nbonadia  veja se esta 100% a tela e maximizada.. Pois o jogo redimenciona as imagem pelo tamanha da tela, Tela pequeno resolução das imagens do jogo fica muito ruim! e o bot nao reconhece!

**Comment by Blackfoxx88** [comment]
@bhrama-br 

it gives me this error then restarts:

[2022-02-18 19:52:42] => SpaceCrypto and Bombcrypto BOT crashed... restarting in 5 seconds.
[2022-02-18 19:52:42] => Exception: Error code from Windows: 0 - The operation completed successfully.
Traceback (most recent call last):
[2022-02-18 19:52:42] ERROR:   File "C:\Users\TOBY\Desktop\spacecrypto-bombcrypto-bot-main\index.py", line 15, in <module>
    runMultiAccount()
[2022-02-18 19:52:42] ERROR:   File "C:\Users\TOBY\Desktop\spacecrypto-bombcrypto-bot-main\src\main_multi_account.py", line 73, in runMultiAccount
    Auth.login()
[2022-02-18 19:52:42] ERROR:   File "C:\Users\TOBY\Desktop\spacecrypto-bombcrypto-bot-main\src\bot\login.py", line 20, in login
    if clickBtn(env.images['ok'], name='okBtn', timeout=5):
[2022-02-18 19:52:42] ERROR:   File "C:\Users\TOBY\Desktop\spacecrypto-bombcrypto-bot-main\src\bot\action.py", line 33, in clickBtn
    matches = getPositions(img, threshold=threshold)
[2022-02-18 19:52:42] ERROR:   File "C:\Users\TOBY\Desktop\spacecrypto-bombcrypto-bot-main\src\bot\action.py", line 68, in getPositions
    img = printScreenForWindow(env.window_object, env.in_login_process == False)
[2022-02-18 19:52:42] ERROR:   File "C:\Users\TOBY\Desktop\spacecrypto-bombcrypto-bot-main\src\utils\image.py", line 24, in printScreenForWindow
    window.activate()
[2022-02-18 19:52:42] ERROR:   File "C:\Users\TOBY\AppData\Local\Programs\Python\Python39\lib\site-packages\pygetwindow\_pygetwindow_win.py", line 246, in activate
    _raiseWithLastError()
[2022-02-18 19:52:42] ERROR:   File "C:\Users\TOBY\AppData\Local\Programs\Python\Python39\lib\site-packages\pygetwindow\_pygetwindow_win.py", line 99, in _raiseWithLastError
- %s' % (errorCode, _formatMessage(errorCode)))
[2022-02-18 19:52:42] ERROR: pygetwindow.PyGetWindowException: Error code from Windows: 0 - The operation completed successfully.

**Comment by bhrama-br** [comment]
Is the game page open?
Do you only have it with the name of spacecrypto or bombcrypto?

**Comment by Blackfoxx88** [comment]
> Is the game page open? Do you only have it with the name of spacecrypto or bombcrypto?

yes 4 browsers are open.

![image](https://user-images.githubusercontent.com/99056652/154687343-94418136-c4a1-444a-a8af-c1911deb31b0.png)

**Comment by bhrama-br** [comment]
need this entire screen.
Bomb at 100% scale.

space depends on the pc resolution.
